spring.application.name=FeatureFlagSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/FeatureFlagSystem
spring.datasource.username=vantablack
spring.datasource.password=dbpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret=replace-this-with-a-long-secret-key-for-jwt-signing-1234567890
security.jwt.expiration-ms=86400000
